# Generated by Django 2.2.4 on 2019-08-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='debtors',
        ),
    ]
