# Generated by Django 2.2.4 on 2019-09-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_debtors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='document',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
