# Generated by Django 2.2.4 on 2019-09-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20190904_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
