# Generated by Django 2.2.4 on 2019-09-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20190904_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtors',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
