# Generated by Django 2.2.4 on 2019-09-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20190904_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='photo',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
    ]
