# Generated by Django 2.2.4 on 2019-09-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_auto_20190904_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
