# Generated by Django 2.2.4 on 2019-09-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_auto_20190904_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('individual_id', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('photo', models.ImageField(default='default.jpeg', upload_to='')),
            ],
        ),
    ]
