# Generated by Django 2.2.4 on 2019-09-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_creditors'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditors',
            name='age',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='creditors',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
        migrations.AddField(
            model_name='debtors',
            name='age',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='debtors',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
    ]
