# Generated by Django 2.2.4 on 2019-09-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_auto_20190905_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtors',
            name='creditors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Creditors'),
        ),
    ]
