# Generated by Django 2.2.4 on 2019-09-12 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_auto_20190911_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditors',
            name='clientid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='debtors',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Creditors'),
        ),
    ]
