# Generated by Django 2.2.4 on 2019-09-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_auto_20190912_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtors',
            old_name='Address',
            new_name='dAddress',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='age',
            new_name='dage',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='email',
            new_name='demail',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='gender',
            new_name='dgender',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='individual_id',
            new_name='dindividual_id',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='name',
            new_name='dname',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='phone',
            new_name='dphone',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='photo',
            new_name='dphoto',
        ),
        migrations.AlterField(
            model_name='debtors',
            name='clientid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agency.Creditors'),
        ),
    ]
