# Generated by Django 2.2.4 on 2019-09-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_auto_20190912_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtors',
            old_name='dAddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='dage',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='demail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='dgender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='dindividual_id',
            new_name='individual_id',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='dname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='dphone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='debtors',
            old_name='dphoto',
            new_name='photo',
        ),
    ]
