# Generated by Django 2.2.4 on 2019-09-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_remove_debtors_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtors',
            name='clientid',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='agency.Creditors'),
        ),
    ]
