# Generated by Django 2.2.4 on 2019-09-12 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_debtors_clientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='clientid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agency.Creditors'),
        ),
    ]
